#!/bin/bash

# include functions.sh
if [ -f "includes/functions.sh" ]; then
  source includes/functions.sh
else
  echo "Fatal error. Could not load functions.sh Exiting..."
  sleep 1s
  exit 1
fi

# Main procedure
while true
  do
  read -p "Are you sure you want to run BACKUP? " run_script
    case $run_script in
    [Yy][Ee][Ss]|[Yy])
    echo "Running backup..."
    sleep 1s

    fn_create_backup_directory
    fn_backup_apache
    fn_backup_nginx
    fn_backup_php_fpm
    fn_backup_webmin
    fn_backup_mysql
#   fn_backup_mysql_databases
    fn_backup_web_apps
    fn_make_archive

    break
    ;;

    [Nn][Oo]|[Nn])
    echo "Aborting..."
    sleep 1s
  break
  ;;
  *)
    echo -e "Please answer with YES or NO."
  ;;
  esac
done
